### ISSUE TITLE
redirect_url is no longer evaluated

### ISSUE THREAD

**Issue by dickhaut** [pagemachine/hairu#39] opened 2018-12-19 10:37 UTC
## Context
We have `redirect_url` as hidden field, which should redirect to the contained value after a successful login. Unfortunately this does not happen anymore.  

## Environment
**TYPO3** 8.7.18
**hairu** 2.1.1

## Process
1. Call a page with the login form where a `redirect_url` is stored in the hidden-field - or call the login with the parameter `/?redirect_url=xy`
2. Log in successfully
3. No forwarding

## Expected result
Redirect after successful login to the url that stored in the value of the hidden field `redirect_url`.

## Current result
Unfortunately it ignores the value of the hidden-field `redirect_url` and do not redirect.

## Possible Fix
It looks like the `signalSlotDispatcher` is not registered correctly.

**Comment by mbrodala** [comment] 2018-12-19 13:50
> Furthermore the file EXT:hairu/Configuration/TypoScript/setup.txt is missing the redirectPage parameter in the login.

What do you mean by that? The mentioned [`settings.login.page` TypoScript constant](https://github.com/pagemachine/hairu/blob/6bf32a6/Configuration/TypoScript/constants.txt#L25) is already used in [the TypoScript setup](https://github.com/pagemachine/hairu/blob/6bf32a6/Configuration/TypoScript/setup.txt#L36).

**Comment by dickhaut** [comment] 2018-12-19 15:04
> > Furthermore the file EXT:hairu/Configuration/TypoScript/setup.txt is missing the redirectPage parameter in the login.
> 
> What do you mean by that? The mentioned [`settings.login.page` TypoScript constant](https://github.com/pagemachine/hairu/blob/6bf32a6/Configuration/TypoScript/constants.txt#L25) is already used in [the TypoScript setup](https://github.com/pagemachine/hairu/blob/6bf32a6/Configuration/TypoScript/setup.txt#L36).

Sorry, that was a mistake. I have extended the TypoScript to specify a redirectPage for a default. 
I have adjusted my issue accordingly.

**Comment by mbrodala** [comment] 2018-12-19 15:06
Thanks for clearing this up.

**Comment by mbrodala** [comment] 2019-01-03 10:43
I just checked on a 8.7.22 instance and `redirect_url` works just fine.

I called the page with the login form with `?redirect_url=...` and this value ended up in the `redirect_url` hidden form field as per default.

Can you add more details about your setup and maybe do some debugging where the `redirect_url` might be lost?

**Comment by m-v-f** [comment] 2019-03-13 20:18
hi, redirect_url works propperly for me, as long as I use e.g.

<input type="hidden" name="redirect_url" value="index.php?id=372"/>

but how can I make the redirect url
a) work with realurl
b) make the redirect URL flexibel

explanation for b)

I have a link button created that either leads to a dedicated fe_user restricted page when already logged in, let's call it download-page-1
when there is nor fe_user logged in, the link leads to the login page. and should redirect after login to download-page-1

the link button on a different page leads to download-page-2 when logged in otherwise to login page, and of cause after login the customer thern should be redirected to download-page-2

hope I explained well what I am trying to achieve, pls bare with my english.

**Comment by mbrodala** [comment] 2019-03-25 10:15
I think I understand your usecase but not really what the issue is. If you use [`typolinkLinkAccessRestrictedPages_addParams`](https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#setup-config-typolinklinkaccessrestrictedpages) you can add the requested but restricted page to the login link and then have a redirect performed after login based on `return_url`.

**Comment by mbrodala** [comment] 2019-04-24 08:55
Closing for now, please leave a comment if you have some news.

**Closed by mbrodala** 2019-04-24 08:55 UTC
Labels: feedback required

**Comment by LotKorn** [comment] 2019-05-16 13:03
@mbrodala The ticket has changed and I can confirm the behaviour.
The Signal 'afterLogin' never gets emitted, becaus the showLogoutFormAction() in AuthenticationController is never called.

It is also rather strange that the action is called Logout but will emit a Login signal. The showLoginFormAction will in fact emit the 'afterLogout' signal...

**Comment by mbrodala** [comment] 2019-05-17 07:08
I can explain the 2nd one: authentication in TYPO3 is rather simple and the only point where we can detect if a login was just completed is in the logout form which is only displayed once logged in. At this point we still have access to all request parameters so we can see if a login was done:

https://github.com/pagemachine/hairu/blob/f0f679a4b1bee34322c681a47caf29c39b2b5bfa/Classes/Controller/AuthenticationController.php#L201
